### PR TITLE
Add names for author in message bubbles

### PR DESCRIPTION
**Pull request by nuzurie**
image

### CODE REVIEW

**Review by yasfahm — APPROVED** [review]
Looks great!! 
Just a suggestion, can the name be written in a different colour for each user?

**Review by car12lin12 — APPROVED** [review]
This looks awesome Zubair :smile:

**Comment by nuzurie** [comment]
> Looks great!! Just a suggestion, can the name be written in a different colour for each user?

I hate u

**Comment by nuzurie** [comment]
> Looks great!! Just a suggestion, can the name be written in a different colour for each user?

If the recruiters see this, this was my idea that she's trying to steal.

**Pull request merged**
