### PR TITLE
[STUD-278]Chat room test

### PR DESCRIPTION
**Pull request by vithura14**
The result of the test is in a video form under the Google drive. You can also run the following command to see the test on your own machine:
`allure open`

### CODE REVIEW

**Review by car12lin12 — COMMENTED** [review]
Similar to the profile tests PR, can you remove changes from App.js and TeamChat.js? Also where did the test report for Login go? I don't see it when I run allure report

**Comment by vithura14** [comment]
> Similar to the profile tests PR, can you remove changes from App.js and TeamChat.js? Also where did the test report for Login go? I don't see it when I run allure report

I added it back! :)

**Comment by vithura14** [comment]
> Similar to the profile tests PR, can you remove changes from App.js and TeamChat.js? Also where did the test report for Login go? I don't see it when I run allure report

As for the login page testing, I disabled those tests since the login page was bypassed in order to run the chat room tests.

**Review by car12lin12 — APPROVED** [review]
Great Job Vithu!!! :rocket:

**Pull request merged**
